// <auto-generated />
using System;
using CRUD_Operation_Employee.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUD_Operation_Employee.Migrations
{
    [DbContext(typeof(EmployeeDBEntities))]
    partial class EmployeeDBEntitiesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRUD_Operation_Employee.Models.Employee", b =>
                {
                    b.Property<int>("employeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employeeId"));

                    b.Property<int>("employeeCode")
                        .HasColumnType("int");

                    b.Property<string>("employeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("employeeSalary")
                        .HasColumnType("float");

                    b.HasKey("employeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("CRUD_Operation_Employee.Models.EmployeeAttendance", b =>
                {
                    b.Property<int>("employeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("attendanceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("isAbsent")
                        .HasColumnType("int");

                    b.Property<int>("isOffday")
                        .HasColumnType("int");

                    b.Property<int>("isPresent")
                        .HasColumnType("int");

                    b.HasKey("employeeId");

                    b.ToTable("EmployeeAttendance");
                });

            modelBuilder.Entity("CRUD_Operation_Employee.Models.EmployeeAttendance", b =>
                {
                    b.HasOne("CRUD_Operation_Employee.Models.Employee", "Employee")
                        .WithOne("Attendance")
                        .HasForeignKey("CRUD_Operation_Employee.Models.EmployeeAttendance", "employeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CRUD_Operation_Employee.Models.Employee", b =>
                {
                    b.Navigation("Attendance")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
